
typedef struct {
	char zlib;
	char bzlib;
	char base;
	char wipe;
//	char rstdin;
	char recurse;
	char progress;
	char slkey;
	char slkeyset;
	char doarchive;
	char *archive;
	char autonamearchive;
	char rmrpath;
	char rmrpaths;
	char *cipher;
	char ciphermode;
	char keylist;
	char commit_key;
	int wtimes;
	int verbose;
	char registerrdb;
	char zlib_level;
	char *zlib_level_string;
	char log;
	char *prog;
	char usekeyfile;
	char genkeyfile;
	char *keyfile;
	size_t gensize;
	char backup;
	//char *erasefile;
	int argc;
	char progress_rhetm;
	char progress_piouemy;
	char noprogress;
	char listarchive;
	char **argv;
	char print_processed_list;
	char menu;
	char resealhottracklist;
	char purgehottracklist;
	//char print_processedrecover_list;
	void (*destructor)(void*);
} opts_s, *opts_t;

extern opts_t opts;
extern opts_t parse_options(int, char **);
